"""One-shot builder for SCIPlot Scientific Figure Catalog knowledge files.

Run from repo root: python knowledge/scientific_figures/_generate_catalog.py
Does not copy third-party R source; metadata / taxonomy only.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PRIVACY = {
    "llm_allowed": ["column_schema", "field_roles", "figure_spec", "desensitized_prompt"],
    "local_only": ["raw_rows", "patient_level_values", "sample_level_values", "dataframe_values"],
}

COMMON_VISUAL = [
    {"name": "width_mm", "description": "Figure width", "default": 89},
    {"name": "height_mm", "description": "Figure height", "default": 70},
    {"name": "font_size", "description": "Base text size (pt)", "default": 7},
    {"name": "legend_position", "description": "Legend placement", "default": "right"},
    {"name": "border", "description": "panel.border none/full", "default": "none"},
]


def src(title: str, url: str, status: str = "verified") -> dict:
    return {"title": title, "url": url, "doi": "", "verification_status": status}


def fig(
    fid: str,
    name: str,
    schema: str,
    packages: list[str],
    questions: list[str],
    contexts: list[str],
    required: list[dict],
    *,
    optional: list[dict] | None = None,
    stats: list[dict] | None = None,
    visual: list[dict] | None = None,
    variants: list[str] | None = None,
    panels: list[str] | None = None,
    keywords: list[str] | None = None,
    intents: list[str] | None = None,
    negative: list[str] | None = None,
    level: str = "core",
    status: str = "catalog_only",
    sources: list[dict] | None = None,
    notes: str = "",
    shapes: list[str] | None = None,
) -> dict:
    category = fid.split(".", 1)[0]
    visual_params = list(visual or []) + [v for v in COMMON_VISUAL if v["name"] not in {x["name"] for x in (visual or [])}]
    return {
        "id": fid,
        "name": name,
        "category": category,
        "scientific_questions": questions,
        "typical_data_contexts": contexts,
        "data_schema_id": schema,
        "required_fields": required,
        "optional_fields": optional or [],
        "accepted_data_shapes": shapes or ["tidy_table"],
        "recommended_r_packages": packages,
        "statistical_parameters": stats or [],
        "visual_parameters": visual_params,
        "variants": variants or [],
        "compatible_panels": panels or [],
        "privacy": PRIVACY,
        "sources": sources
        or [
            src("ggplot2 theme reference", "https://ggplot2.tidyverse.org/reference/theme.html"),
        ],
        "retrieval_keywords": keywords or [],
        "user_intent_examples": intents or [],
        "negative_intents": negative or [],
        "capability_level": level,
        "implementation_status": status,
        "notes": notes,
    }


FIGURES: list[dict] = []

# ---- basic_statistics ----
FIGURES += [
    fig(
        "basic_statistics.boxplot",
        "Boxplot",
        "group_numeric_table",
        ["ggplot2", "ggpubr"],
        ["Compare distributions of continuous variables across groups"],
        ["clinical", "RNA-seq", "proteomics"],
        [
            {"role": "group", "type": "categorical", "description": "Grouping / category variable"},
            {"role": "value", "type": "numeric", "description": "Continuous outcome"},
        ],
        optional=[
            {"role": "sample_id", "type": "string", "description": "Optional sample identifier"},
            {"role": "annotation", "type": "string", "description": "Optional annotation / facet label"},
        ],
        stats=[{"name": "test_method", "description": "Optional comparison test", "default": "wilcox"}],
        visual=[
            {"name": "variant", "description": "Geometry variant: boxplot | violin", "default": "boxplot"},
            {"name": "fill", "description": "Fill aesthetic (column role or fixed color)", "default": "group"},
            {"name": "alpha", "description": "Fill / point transparency", "default": 0.7},
            {"name": "line_width", "description": "Box / violin outline width", "default": 0.5},
            {"name": "point_size", "description": "Jitter point size when overlay enabled", "default": 1.2},
            {"name": "point_jitter", "description": "Overlay jitter points", "default": False},
            {"name": "fill_palette", "default": "npg"},
        ],
        variants=["boxplot", "violin"],
        keywords=["boxplot", "箱线图", "group comparison", "violin"],
        intents=["比较各组表达分布", "画箱线图"],
        negative=["画生存曲线", "画火山图"],
        status="execution_verified",
        notes="Implemented via Generic Figure Engine BoxplotStrategy (not a dedicated agent).",
    ),
    fig(
        "basic_statistics.violin",
        "Violin plot",
        "grouped_numeric_table",
        ["ggplot2", "ggpubr"],
        ["What is the distribution shape of a continuous variable by group?"],
        ["RNA-seq", "single-cell", "clinical"],
        [{"role": "group", "type": "categorical"}, {"role": "value", "type": "numeric"}],
        keywords=["violin", "小提琴图"],
        intents=["用小提琴图看分布"],
    ),
    fig(
        "basic_statistics.scatter",
        "Scatter plot",
        "two_numeric_table",
        ["ggplot2", "ggpubr"],
        ["Are two continuous variables associated?"],
        ["RNA-seq", "clinical", "proteomics"],
        [{"role": "x", "type": "numeric", "description": "X-axis continuous variable"}, {"role": "y", "type": "numeric", "description": "Y-axis continuous variable"}],
        optional=[
            {"role": "group", "type": "categorical", "description": "Optional color grouping"},
            {"role": "size", "type": "numeric", "description": "Optional point-size variable"},
        ],
        stats=[{"name": "correlation_method", "default": "pearson"}],
        visual=[
            {"name": "alpha", "description": "Point transparency", "default": 0.7},
            {"name": "point_size", "description": "Base point size when size aesthetic unused", "default": 1.6},
            {"name": "line_width", "description": "Axis line width", "default": 0.5},
            {"name": "point_color", "description": "Fixed point color", "default": "#3C5488"},
        ],
        keywords=["scatter", "散点图", "correlation"],
        intents=["看两个指标相关性", "绘制散点图"],
        status="execution_verified",
        notes="Implemented via Generic Figure Engine ScatterStrategy (LLM maps columns only; R is rule-generated).",
    ),
    fig(
        "basic_statistics.barplot",
        "Bar plot",
        "grouped_count_table",
        ["ggplot2"],
        ["How do counts or proportions differ across categories?"],
        ["clinical", "microbiome", "single-cell"],
        [{"role": "category", "type": "categorical"}, {"role": "value", "type": "numeric"}],
        keywords=["barplot", "柱状图"],
    ),
    fig(
        "basic_statistics.histogram",
        "Histogram",
        "single_numeric_table",
        ["ggplot2"],
        ["What is the univariate distribution of a continuous variable?"],
        ["QC", "clinical"],
        [{"role": "value", "type": "numeric"}],
        stats=[{"name": "binwidth", "default": None}],
        keywords=["histogram", "直方图"],
    ),
    fig(
        "basic_statistics.density",
        "Density plot",
        "grouped_numeric_table",
        ["ggplot2", "ggridges"],
        ["How do density distributions compare across groups?"],
        ["RNA-seq", "clinical"],
        [{"role": "value", "type": "numeric"}],
        optional=[{"role": "group", "type": "categorical"}],
        keywords=["density", "密度图"],
    ),
    fig(
        "basic_statistics.beeswarm",
        "Beeswarm plot",
        "grouped_numeric_table",
        ["ggplot2", "ggbeeswarm"],
        ["How are individual observations distributed within groups without overplotting?"],
        ["clinical", "RNA-seq"],
        [{"role": "group", "type": "categorical"}, {"role": "value", "type": "numeric"}],
        level="advanced",
        keywords=["beeswarm", "蜂群图"],
    ),
    fig(
        "basic_statistics.ridge",
        "Ridge plot",
        "grouped_numeric_table",
        ["ggridges", "ggplot2"],
        ["How do many group-wise densities compare compactly?"],
        ["RNA-seq", "proteomics"],
        [{"role": "group", "type": "categorical"}, {"role": "value", "type": "numeric"}],
        level="advanced",
        keywords=["ridge", "山脊图", "ggridges"],
    ),
    fig(
        "basic_statistics.bland_altman",
        "Bland–Altman plot",
        "paired_numeric_table",
        ["ggplot2"],
        ["Do two measurement methods agree?"],
        ["clinical", "assay QC"],
        [{"role": "method_a", "type": "numeric"}, {"role": "method_b", "type": "numeric"}],
        level="advanced",
        keywords=["Bland-Altman", "method agreement"],
    ),
    fig(
        "basic_statistics.correlation_heatmap",
        "Correlation heatmap",
        "numeric_matrix",
        ["ggplot2", "ComplexHeatmap"],
        ["Which features or samples are correlated?"],
        ["RNA-seq", "proteomics", "multiomics"],
        [{"role": "feature_or_sample_matrix", "type": "numeric_matrix"}],
        shapes=["matrix"],
        stats=[{"name": "correlation_method", "default": "pearson"}],
        keywords=["correlation heatmap", "相关热图"],
    ),
]

# ---- transcriptomics ----
FIGURES += [
    fig(
        "transcriptomics.volcano",
        "Volcano plot",
        "differential_expression_table",
        ["ggplot2", "ggrepel"],
        ["Which features show statistically significant differential abundance or expression?"],
        ["RNA-seq", "proteomics", "metabolomics"],
        [
            {"role": "feature_id", "type": "string"},
            {"role": "effect_size", "type": "numeric"},
            {"role": "significance", "type": "numeric"},
        ],
        stats=[
            {"name": "log2FC_threshold", "default": 1.0},
            {"name": "significance_threshold", "default": 0.05},
            {"name": "significance_metric", "default": "fdr"},
            {"name": "multiple_testing_method", "default": "BH"},
        ],
        visual=[
            {"name": "point_size", "default": 1.5},
            {"name": "alpha", "default": 0.7},
            {"name": "up_color", "default": "#E64B35"},
            {"name": "down_color", "default": "#4DBBD5"},
            {"name": "neutral_color", "default": "#B0B0B0"},
            {"name": "label_count", "default": 10},
            {"name": "label_repel", "default": True},
            {"name": "threshold_line_width", "default": 0.35},
            {"name": "threshold_line_type", "default": "dashed"},
        ],
        variants=["classic", "labeled", "multi_contrast"],
        panels=["transcriptomics.DEG_heatmap", "enrichment.GSEA_running_score", "enrichment.ORA_dotplot"],
        keywords=["volcano", "火山图", "DEG", "differential expression", "FDR", "fold change", "差异基因"],
        intents=[
            "我想展示两组RNA-seq差异基因",
            "哪些基因上调和下调最明显",
            "做一个带FDR和fold-change的差异图",
        ],
        negative=["展示所有样本之间的表达相似性", "展示患者生存差异"],
        status="qc_verified",
        sources=[
            src("ggplot2", "https://ggplot2.tidyverse.org/"),
            src("ggrepel", "https://cran.r-project.org/package=ggrepel"),
            src("SCIPlot AI existing volcano implementation", "schemas/figure_spec.py"),
        ],
        notes="Mapped to existing SCIPlot Volcano Spec / R / QC pipeline.",
    ),
    fig(
        "transcriptomics.MA_plot",
        "MA plot",
        "differential_expression_table",
        ["ggplot2"],
        ["How does differential effect size relate to mean abundance?"],
        ["RNA-seq", "microarray"],
        [{"role": "mean_expression", "type": "numeric"}, {"role": "effect_size", "type": "numeric"}],
        optional=[{"role": "significance", "type": "numeric"}],
        keywords=["MA plot", "MAplot"],
        panels=["transcriptomics.volcano"],
    ),
    fig(
        "transcriptomics.DEG_heatmap",
        "DEG heatmap",
        "expression_matrix_with_annotation",
        ["ComplexHeatmap", "circlize"],
        ["How do selected DEGs pattern across samples?"],
        ["RNA-seq"],
        [{"role": "feature_id", "type": "string"}, {"role": "sample_expression", "type": "numeric_matrix"}],
        shapes=["matrix"],
        level="advanced",
        stats=[{"name": "scaling", "default": "zscore"}, {"name": "clustering_method", "default": "complete"}],
        keywords=["DEG heatmap", "差异基因热图"],
        panels=["transcriptomics.volcano"],
        sources=[src("ComplexHeatmap", "https://jokergoo.github.io/ComplexHeatmap-reference/book/")],
    ),
    fig(
        "transcriptomics.expression_boxplot",
        "Gene expression boxplot",
        "long_expression_table",
        ["ggplot2", "ggpubr"],
        ["How does a gene's expression differ across conditions?"],
        ["RNA-seq"],
        [{"role": "feature_id", "type": "string"}, {"role": "group", "type": "categorical"}, {"role": "expression", "type": "numeric"}],
        keywords=["expression boxplot", "基因表达箱线图"],
    ),
    fig(
        "transcriptomics.expression_violin",
        "Gene expression violin",
        "long_expression_table",
        ["ggplot2"],
        ["What is the expression distribution of selected genes by group?"],
        ["RNA-seq", "single-cell"],
        [{"role": "feature_id", "type": "string"}, {"role": "group", "type": "categorical"}, {"role": "expression", "type": "numeric"}],
        keywords=["expression violin"],
    ),
    fig(
        "transcriptomics.PCA",
        "PCA plot",
        "expression_matrix_with_annotation",
        ["ggplot2"],
        ["Do samples separate by biological condition in transcriptome space?"],
        ["RNA-seq", "proteomics"],
        [{"role": "sample_id", "type": "string"}, {"role": "PC1", "type": "numeric"}, {"role": "PC2", "type": "numeric"}],
        optional=[{"role": "group", "type": "categorical"}],
        keywords=["PCA", "主成分"],
        intents=["看样本是否分群"],
        negative=["画生存曲线"],
    ),
    fig(
        "transcriptomics.sample_correlation",
        "Sample–sample correlation",
        "numeric_matrix",
        ["ComplexHeatmap", "ggplot2"],
        ["How similar are transcriptome profiles across samples?"],
        ["RNA-seq"],
        [{"role": "sample_matrix", "type": "numeric_matrix"}],
        shapes=["matrix"],
        keywords=["sample correlation", "样本相关"],
    ),
    fig(
        "transcriptomics.expression_profile",
        "Expression profile / trend lines",
        "long_expression_table",
        ["ggplot2"],
        ["How does expression of selected features change across ordered conditions?"],
        ["RNA-seq", "time_series"],
        [{"role": "feature_id", "type": "string"}, {"role": "condition_order", "type": "ordered"}, {"role": "expression", "type": "numeric"}],
        keywords=["expression profile", "表达趋势"],
    ),
    fig(
        "transcriptomics.multi_volcano",
        "Multi-contrast volcano",
        "differential_expression_table",
        ["ggplot2", "ggrepel", "patchwork"],
        ["How do DE results compare across multiple contrasts?"],
        ["RNA-seq"],
        [{"role": "feature_id", "type": "string"}, {"role": "effect_size", "type": "numeric"}, {"role": "significance", "type": "numeric"}, {"role": "contrast", "type": "categorical"}],
        level="advanced",
        keywords=["multi volcano", "多组火山图"],
    ),
]

# ---- enrichment ----
FIGURES += [
    fig(
        "enrichment.ORA_dotplot",
        "ORA enrichment dotplot",
        "enrichment_table",
        ["clusterProfiler", "enrichplot", "ggplot2"],
        ["Which biological terms are over-represented in a gene set?"],
        ["RNA-seq", "proteomics"],
        [{"role": "term", "type": "string"}, {"role": "significance", "type": "numeric"}, {"role": "gene_ratio", "type": "numeric"}],
        optional=[{"role": "count", "type": "integer"}],
        stats=[{"name": "p_adjust_method", "default": "BH"}, {"name": "qvalue_cutoff", "default": 0.05}],
        keywords=["ORA", "GO", "KEGG", "富集气泡图", "dotplot"],
        sources=[src("enrichplot", "https://bioconductor.org/packages/enrichplot/")],
    ),
    fig(
        "enrichment.ORA_barplot",
        "ORA enrichment barplot",
        "enrichment_table",
        ["clusterProfiler", "enrichplot", "ggplot2"],
        ["Which enriched terms rank highest by significance or count?"],
        ["RNA-seq"],
        [{"role": "term", "type": "string"}, {"role": "significance", "type": "numeric"}],
        keywords=["enrichment barplot", "富集柱状图"],
    ),
    fig(
        "enrichment.GSEA_running_score",
        "GSEA running-score plot",
        "gsea_result_table",
        ["clusterProfiler", "enrichplot"],
        ["Is a gene set coordinated up or down in a ranked list?"],
        ["RNA-seq"],
        [{"role": "term", "type": "string"}, {"role": "running_score", "type": "numeric"}, {"role": "rank", "type": "integer"}],
        stats=[{"name": "nPerm", "default": 1000}, {"name": "minGSSize", "default": 10}],
        keywords=["GSEA", "running score"],
        panels=["transcriptomics.volcano", "enrichment.GSEA_ridge"],
        sources=[src("clusterProfiler", "https://bioconductor.org/packages/clusterProfiler/")],
    ),
    fig(
        "enrichment.GSEA_ridge",
        "GSEA ridge plot",
        "gsea_result_table",
        ["enrichplot", "ggridges"],
        ["How do NES distributions compare across multiple gene sets?"],
        ["RNA-seq"],
        [{"role": "term", "type": "string"}, {"role": "NES", "type": "numeric"}],
        level="advanced",
        keywords=["GSEA ridge"],
    ),
    fig(
        "enrichment.enrichment_emap",
        "Enrichment map",
        "enrichment_table",
        ["enrichplot", "igraph"],
        ["Which enriched terms cluster by gene overlap?"],
        ["RNA-seq"],
        [{"role": "term", "type": "string"}, {"role": "gene_ids", "type": "string_list"}],
        level="advanced",
        keywords=["emap", "enrichment map"],
    ),
    fig(
        "enrichment.enrichment_cnet",
        "Category netplot (cnet)",
        "enrichment_table",
        ["enrichplot"],
        ["How do genes connect selected enriched terms?"],
        ["RNA-seq"],
        [{"role": "term", "type": "string"}, {"role": "gene_ids", "type": "string_list"}],
        level="advanced",
        keywords=["cnetplot", "category net"],
    ),
    fig(
        "enrichment.GO_hierarchy",
        "GO hierarchy plot",
        "enrichment_table",
        ["enrichplot", "GOSemSim"],
        ["How are significant GO terms organized in the ontology DAG?"],
        ["RNA-seq"],
        [{"role": "term", "type": "string"}, {"role": "significance", "type": "numeric"}],
        level="advanced",
        keywords=["GO plot", "GO hierarchy"],
    ),
]

# ---- clinical ----
FIGURES += [
    fig(
        "clinical.Kaplan_Meier",
        "Kaplan–Meier survival curve",
        "survival_table",
        ["survival", "survminer", "ggplot2"],
        ["Do survival probabilities differ between groups over time?"],
        ["TCGA", "clinical cohort"],
        [{"role": "time", "type": "numeric"}, {"role": "status", "type": "binary"}, {"role": "group", "type": "categorical"}],
        stats=[{"name": "conf_int", "default": True}, {"name": "pval_method", "default": "logrank"}],
        keywords=["KM", "Kaplan-Meier", "生存曲线", "survminer"],
        intents=["比较高低风险组生存"],
        negative=["画差异火山图"],
        panels=["clinical.ROC", "clinical.Cox_forest"],
        sources=[src("survminer", "https://cran.r-project.org/package=survminer")],
    ),
    fig(
        "clinical.Cox_forest",
        "Cox forest plot",
        "cox_result_table",
        ["survival", "forestplot", "ggplot2"],
        ["Which covariates associate with hazard?"],
        ["clinical"],
        [{"role": "covariate", "type": "string"}, {"role": "HR", "type": "numeric"}, {"role": "CI_low", "type": "numeric"}, {"role": "CI_high", "type": "numeric"}],
        keywords=["forest", "Cox", "HR"],
        level="advanced",
    ),
    fig(
        "clinical.ROC",
        "ROC curve",
        "binary_prediction_table",
        ["pROC", "ggplot2"],
        ["How well does a continuous marker classify a binary outcome?"],
        ["clinical", "biomarker"],
        [{"role": "score", "type": "numeric"}, {"role": "label", "type": "binary"}],
        stats=[{"name": "direction", "default": "auto"}],
        keywords=["ROC", "AUC", "受试者工作特征"],
        sources=[src("pROC", "https://cran.r-project.org/package=pROC")],
    ),
    fig(
        "clinical.time_dependent_ROC",
        "Time-dependent ROC",
        "survival_prediction_table",
        ["timeROC", "survival", "ggplot2"],
        ["How does discriminatory ability change at landmark survival times?"],
        ["clinical"],
        [{"role": "time", "type": "numeric"}, {"role": "status", "type": "binary"}, {"role": "marker", "type": "numeric"}],
        level="advanced",
        keywords=["timeROC", "time-dependent ROC"],
        sources=[src("timeROC", "https://cran.r-project.org/package=timeROC")],
    ),
    fig(
        "clinical.calibration",
        "Calibration plot",
        "prediction_probability_table",
        ["ggplot2", "rms"],
        ["Do predicted risks match observed event rates?"],
        ["clinical", "prognostic model"],
        [{"role": "predicted_risk", "type": "numeric"}, {"role": "observed_outcome", "type": "binary"}],
        level="advanced",
        keywords=["calibration", "校准曲线"],
    ),
    fig(
        "clinical.decision_curve",
        "Decision curve analysis",
        "prediction_probability_table",
        ["rmda", "ggplot2"],
        ["Across threshold probabilities, does the model add net clinical benefit?"],
        ["clinical"],
        [{"role": "predicted_risk", "type": "numeric"}, {"role": "observed_outcome", "type": "binary"}],
        level="advanced",
        keywords=["DCA", "decision curve"],
        sources=[src("rmda", "https://cran.r-project.org/package=rmda", "unverified")],
    ),
    fig(
        "clinical.nomogram",
        "Nomogram",
        "cox_model_input",
        ["rms", "survival"],
        ["How can individual covariate values be translated into predicted risk?"],
        ["clinical"],
        [{"role": "covariates", "type": "mixed"}, {"role": "outcome_model", "type": "model_object"}],
        level="advanced",
        keywords=["nomogram", "列线图"],
    ),
    fig(
        "clinical.competing_risk",
        "Competing-risk cumulative incidence",
        "competing_risk_table",
        ["cmprsk", "ggplot2"],
        ["How do event probabilities accumulate when competing events exist?"],
        ["clinical"],
        [{"role": "time", "type": "numeric"}, {"role": "event_type", "type": "categorical"}, {"role": "group", "type": "categorical"}],
        level="advanced",
        keywords=["competing risk", "CIF"],
    ),
    fig(
        "clinical.swimmer",
        "Swimmer plot",
        "patient_timeline_table",
        ["ggplot2"],
        ["How do individual patient treatment courses and responses unfold over time?"],
        ["clinical trial"],
        [{"role": "patient_id", "type": "string"}, {"role": "start", "type": "numeric"}, {"role": "end", "type": "numeric"}],
        level="advanced",
        keywords=["swimmer", "泳道图"],
    ),
    fig(
        "clinical.risk_score",
        "Risk-score distribution / strata plot",
        "survival_prediction_table",
        ["ggplot2", "survminer"],
        ["How are model risk scores distributed and linked to outcome strata?"],
        ["clinical"],
        [{"role": "sample_id", "type": "string"}, {"role": "risk_score", "type": "numeric"}, {"role": "group", "type": "categorical"}],
        keywords=["risk score", "风险评分"],
    ),
]

# ---- machine_learning ----
FIGURES += [
    fig(
        "machine_learning.confusion_matrix",
        "Confusion matrix heatmap",
        "classification_result_table",
        ["ggplot2"],
        ["Where do classification errors concentrate?"],
        ["ML biomarker", "imaging"],
        [{"role": "truth", "type": "categorical"}, {"role": "prediction", "type": "categorical"}],
        keywords=["confusion matrix", "混淆矩阵"],
    ),
    fig(
        "machine_learning.feature_importance",
        "Feature importance bar/dot plot",
        "feature_importance_table",
        ["ggplot2"],
        ["Which features contribute most to a predictive model?"],
        ["ML", "radiomics"],
        [{"role": "feature", "type": "string"}, {"role": "importance", "type": "numeric"}],
        keywords=["feature importance", "特征重要性"],
    ),
    fig(
        "machine_learning.lasso_path",
        "LASSO regularization path",
        "glmnet_path_table",
        ["glmnet", "ggplot2"],
        ["How do coefficients shrink across lambda?"],
        ["prognostic model"],
        [{"role": "lambda", "type": "numeric"}, {"role": "coefficient", "type": "numeric"}, {"role": "feature", "type": "string"}],
        level="advanced",
        keywords=["lasso", "glmnet"],
    ),
    fig(
        "machine_learning.ROC_multi_model",
        "Multi-model ROC comparison",
        "binary_prediction_table",
        ["pROC", "ggplot2"],
        ["Which candidate models discriminate better?"],
        ["ML", "clinical"],
        [{"role": "score", "type": "numeric"}, {"role": "label", "type": "binary"}, {"role": "model", "type": "categorical"}],
        keywords=["multi ROC", "模型比较ROC"],
    ),
    fig(
        "machine_learning.learning_curve",
        "Learning / validation curve",
        "model_metric_by_size_table",
        ["ggplot2"],
        ["How does performance change with training set size or hyperparameter?"],
        ["ML"],
        [{"role": "train_size", "type": "numeric"}, {"role": "metric", "type": "numeric"}, {"role": "split", "type": "categorical"}],
        level="advanced",
        keywords=["learning curve"],
    ),
]

# ---- single_cell ----
FIGURES += [
    fig(
        "single_cell.UMAP",
        "UMAP embedding",
        "single_cell_embedding",
        ["Seurat", "ggplot2"],
        ["How do cells organize in a low-dimensional embedding?"],
        ["scRNA-seq"],
        [{"role": "cell_id", "type": "string"}, {"role": "dimension_1", "type": "numeric"}, {"role": "dimension_2", "type": "numeric"}],
        optional=[{"role": "group", "type": "categorical"}],
        keywords=["UMAP", "单细胞降维"],
        panels=["single_cell.DotPlot", "single_cell.Violin_sc"],
        sources=[src("Seurat", "https://satijalab.org/seurat/")],
    ),
    fig(
        "single_cell.tSNE",
        "t-SNE embedding",
        "single_cell_embedding",
        ["Seurat", "ggplot2"],
        ["How do cells cluster in t-SNE space?"],
        ["scRNA-seq"],
        [{"role": "cell_id", "type": "string"}, {"role": "dimension_1", "type": "numeric"}, {"role": "dimension_2", "type": "numeric"}],
        keywords=["tSNE", "t-SNE"],
    ),
    fig(
        "single_cell.FeaturePlot",
        "FeaturePlot (gene on embedding)",
        "single_cell_embedding_with_feature",
        ["Seurat"],
        ["Where is a gene expressed on the embedding?"],
        ["scRNA-seq"],
        [{"role": "cell_id", "type": "string"}, {"role": "dimension_1", "type": "numeric"}, {"role": "dimension_2", "type": "numeric"}, {"role": "feature_value", "type": "numeric"}],
        keywords=["FeaturePlot", "基因表达UMAP"],
    ),
    fig(
        "single_cell.DotPlot",
        "Marker DotPlot",
        "single_cell_dot_summary",
        ["Seurat", "ggplot2"],
        ["Which markers define cell identities (pct.exp × average expression)?"],
        ["scRNA-seq"],
        [{"role": "feature", "type": "string"}, {"role": "identity", "type": "categorical"}, {"role": "avg_exp", "type": "numeric"}, {"role": "pct_exp", "type": "numeric"}],
        keywords=["DotPlot", "marker bubble"],
    ),
    fig(
        "single_cell.Violin_sc",
        "Single-cell violin",
        "long_expression_table",
        ["Seurat", "ggplot2"],
        ["How is marker expression distributed across identities?"],
        ["scRNA-seq"],
        [{"role": "feature_id", "type": "string"}, {"role": "group", "type": "categorical"}, {"role": "expression", "type": "numeric"}],
        keywords=["sc violin", "VlnPlot"],
    ),
    fig(
        "single_cell.marker_heatmap",
        "Marker heatmap",
        "expression_matrix_with_annotation",
        ["Seurat", "ComplexHeatmap"],
        ["Which markers distinguish annotated clusters?"],
        ["scRNA-seq"],
        [{"role": "feature_id", "type": "string"}, {"role": "identity", "type": "categorical"}],
        shapes=["matrix"],
        level="advanced",
        keywords=["marker heatmap"],
    ),
    fig(
        "single_cell.cell_proportion",
        "Cell-type proportion stacked bar",
        "cell_proportion_table",
        ["ggplot2"],
        ["How do cell-type compositions change across samples/conditions?"],
        ["scRNA-seq"],
        [{"role": "sample", "type": "categorical"}, {"role": "cell_type", "type": "categorical"}, {"role": "proportion", "type": "numeric"}],
        keywords=["cell proportion", "细胞比例"],
    ),
    fig(
        "single_cell.pseudotime",
        "Pseudotime scatter on embedding",
        "single_cell_embedding",
        ["Seurat", "ggplot2"],
        ["How does inferred progression score vary across cells?"],
        ["scRNA-seq"],
        [{"role": "cell_id", "type": "string"}, {"role": "dimension_1", "type": "numeric"}, {"role": "dimension_2", "type": "numeric"}, {"role": "pseudotime", "type": "numeric"}],
        level="advanced",
        keywords=["pseudotime"],
    ),
    fig(
        "single_cell.trajectory",
        "Trajectory / lineage graph",
        "trajectory_graph",
        ["slingshot", "ggplot2"],
        ["What lineage structure connects cell states?"],
        ["scRNA-seq"],
        [{"role": "node", "type": "string"}, {"role": "edge", "type": "pair"}],
        level="experimental",
        keywords=["trajectory", "slingshot"],
    ),
    fig(
        "single_cell.composition_plot",
        "Composition / mosaic plot",
        "cell_proportion_table",
        ["ggplot2"],
        ["How do categorical compositions differ visually across conditions?"],
        ["scRNA-seq"],
        [{"role": "sample", "type": "categorical"}, {"role": "cell_type", "type": "categorical"}, {"role": "count", "type": "integer"}],
        keywords=["composition plot"],
    ),
]

# ---- spatial_omics ----
FIGURES += [
    fig(
        "spatial_omics.spatial_feature",
        "Spatial feature map",
        "spatial_spot_table",
        ["Seurat", "ggplot2"],
        ["Where is a gene or score localized in tissue coordinates?"],
        ["Visium", "spatial transcriptomics"],
        [{"role": "spot_id", "type": "string"}, {"role": "x", "type": "numeric"}, {"role": "y", "type": "numeric"}, {"role": "feature_value", "type": "numeric"}],
        level="advanced",
        keywords=["spatial feature", "空间表达"],
    ),
    fig(
        "spatial_omics.spatial_clusters",
        "Spatial cluster map",
        "spatial_spot_table",
        ["Seurat", "ggplot2"],
        ["How are spatial domains arranged in tissue?"],
        ["spatial transcriptomics"],
        [{"role": "spot_id", "type": "string"}, {"role": "x", "type": "numeric"}, {"role": "y", "type": "numeric"}, {"role": "cluster", "type": "categorical"}],
        level="advanced",
        keywords=["spatial cluster"],
    ),
]

# ---- mutation_genomics ----
FIGURES += [
    fig(
        "mutation_genomics.oncoplot",
        "Oncoplot / oncoPrint",
        "mutation_table",
        ["maftools", "ComplexHeatmap"],
        ["Which genes are recurrently altered across samples?"],
        ["WES", "panel sequencing"],
        [{"role": "sample", "type": "string"}, {"role": "gene", "type": "string"}, {"role": "variant_class", "type": "categorical"}],
        level="advanced",
        keywords=["oncoplot", "oncoPrint", "瀑布图"],
        panels=["mutation_genomics.TMB", "mutation_genomics.mutation_frequency"],
        sources=[src("maftools", "https://bioconductor.org/packages/maftools/")],
    ),
    fig(
        "mutation_genomics.mutation_frequency",
        "Mutation frequency barplot",
        "mutation_summary_table",
        ["maftools", "ggplot2"],
        ["What fraction of samples carry each gene alteration?"],
        ["cancer genomics"],
        [{"role": "gene", "type": "string"}, {"role": "frequency", "type": "numeric"}],
        keywords=["mutation frequency"],
    ),
    fig(
        "mutation_genomics.lollipop",
        "Lollipop mutation plot",
        "mutation_protein_table",
        ["maftools", "ggplot2"],
        ["Where do mutations fall along a protein domain map?"],
        ["cancer genomics"],
        [{"role": "gene", "type": "string"}, {"role": "aa_position", "type": "integer"}, {"role": "variant_class", "type": "categorical"}],
        level="advanced",
        keywords=["lollipop", "棒棒糖图"],
    ),
    fig(
        "mutation_genomics.TiTv",
        "Ti/Tv summary",
        "mutation_table",
        ["maftools"],
        ["What are transition/transversion patterns?"],
        ["WES"],
        [{"role": "sample", "type": "string"}, {"role": "ref", "type": "string"}, {"role": "alt", "type": "string"}],
        level="advanced",
        keywords=["TiTv", "titv"],
    ),
    fig(
        "mutation_genomics.cooccurrence",
        "Mutation co-occurrence heatmap",
        "mutation_table",
        ["maftools", "ggplot2"],
        ["Which gene pairs co-occur more than expected?"],
        ["cancer genomics"],
        [{"role": "sample", "type": "string"}, {"role": "gene", "type": "string"}],
        level="advanced",
        keywords=["co-occurrence"],
    ),
    fig(
        "mutation_genomics.mutual_exclusivity",
        "Mutual exclusivity plot",
        "mutation_table",
        ["maftools"],
        ["Which alterations are mutually exclusive?"],
        ["cancer genomics"],
        [{"role": "sample", "type": "string"}, {"role": "gene", "type": "string"}],
        level="advanced",
        keywords=["mutual exclusivity"],
    ),
    fig(
        "mutation_genomics.CNV_plot",
        "CNV landscape / heatmap",
        "cnv_segment_table",
        ["ComplexHeatmap", "ggplot2"],
        ["Where are copy-number gains/losses across the genome?"],
        ["SNP array", "WES CNV"],
        [{"role": "sample", "type": "string"}, {"role": "chrom", "type": "string"}, {"role": "start", "type": "integer"}, {"role": "end", "type": "integer"}, {"role": "segment_mean", "type": "numeric"}],
        level="advanced",
        keywords=["CNV", "copy number"],
    ),
    fig(
        "mutation_genomics.TMB",
        "Tumor mutation burden plot",
        "tmb_table",
        ["maftools", "ggplot2"],
        ["How does TMB distribute across samples or subtypes?"],
        ["WES", "immunotherapy cohort"],
        [{"role": "sample", "type": "string"}, {"role": "TMB", "type": "numeric"}],
        keywords=["TMB", "tumor mutation burden"],
    ),
]

# ---- genomics ----
FIGURES += [
    fig(
        "genomics.genomic_track",
        "Genomic track / coverage plot",
        "genomic_interval_table",
        ["ggplot2", "ggbio"],
        ["How do signal tracks align along genomic coordinates?"],
        ["ChIP-seq", "ATAC-seq"],
        [{"role": "chrom", "type": "string"}, {"role": "start", "type": "integer"}, {"role": "end", "type": "integer"}, {"role": "score", "type": "numeric"}],
        level="advanced",
        keywords=["genome track", "coverage"],
    ),
    fig(
        "genomics.manhattan",
        "Manhattan plot",
        "gwas_association_table",
        ["ggplot2", "qqman"],
        ["Which genomic loci associate with a trait?"],
        ["GWAS"],
        [{"role": "chrom", "type": "string"}, {"role": "position", "type": "integer"}, {"role": "pvalue", "type": "numeric"}],
        stats=[{"name": "significance_line", "default": 5e-8}],
        keywords=["manhattan", "GWAS"],
    ),
    fig(
        "genomics.circos_genome",
        "Circos / circular genome plot",
        "multi_track_genomic_table",
        ["circlize"],
        ["How can multi-omics genomic relations be shown in circular layout?"],
        ["cancer genomics", "comparative genomics"],
        [{"role": "chrom", "type": "string"}, {"role": "start", "type": "integer"}, {"role": "end", "type": "integer"}],
        level="experimental",
        keywords=["circos", "circlize"],
        sources=[src("circlize", "https://cran.r-project.org/package=circlize")],
    ),
]

# ---- comparative_genomics ----
FIGURES += [
    fig(
        "comparative_genomics.phylogenetic_tree",
        "Phylogenetic tree",
        "tree_newick",
        ["ggtree"],
        ["How are genomes/strains related phylogenetically?"],
        ["bacterial genomics", "viral genomics"],
        [{"role": "tree", "type": "newick"}],
        level="advanced",
        keywords=["phylogenetic tree", "进化树", "ggtree"],
        sources=[src("ggtree", "https://bioconductor.org/packages/ggtree/")],
    ),
    fig(
        "comparative_genomics.tree_metadata",
        "Tree with tip metadata",
        "tree_with_metadata",
        ["ggtree", "ggtreeExtra"],
        ["How do phenotypes map onto phylogeny?"],
        ["microbial genomics"],
        [{"role": "tree", "type": "newick"}, {"role": "tip_metadata", "type": "table"}],
        level="advanced",
        keywords=["tree metadata", "ggtreeExtra"],
    ),
    fig(
        "comparative_genomics.tree_heatmap",
        "Tree + heatmap composite",
        "tree_with_matrix",
        ["ggtree", "ggtreeExtra"],
        ["How do multi-feature profiles align with phylogeny?"],
        ["comparative genomics"],
        [{"role": "tree", "type": "newick"}, {"role": "feature_matrix", "type": "numeric_matrix"}],
        level="advanced",
        keywords=["tree heatmap"],
    ),
    fig(
        "comparative_genomics.gene_presence_absence",
        "Gene presence/absence heatmap",
        "gene_pa_matrix",
        ["ComplexHeatmap", "ggplot2"],
        ["Which accessory genes vary across genomes?"],
        ["pangenome"],
        [{"role": "genome", "type": "string"}, {"role": "gene", "type": "string"}, {"role": "presence", "type": "binary"}],
        shapes=["matrix"],
        level="advanced",
        keywords=["pangenome", "presence absence"],
    ),
    fig(
        "comparative_genomics.synteny",
        "Synteny plot",
        "synteny_link_table",
        ["gggenomes", "ggplot2"],
        ["How are homologous blocks arranged between genomes?"],
        ["comparative genomics"],
        [{"role": "genome_a", "type": "string"}, {"role": "genome_b", "type": "string"}, {"role": "start_a", "type": "integer"}, {"role": "start_b", "type": "integer"}],
        level="experimental",
        keywords=["synteny", "共线性"],
        sources=[src("gggenomes", "https://github.com/thackl/gggenomes", "unverified")],
    ),
    fig(
        "comparative_genomics.gene_neighborhood",
        "Gene neighborhood / gggenes",
        "gene_feature_table",
        ["gggenes", "ggplot2"],
        ["How are neighboring genes organized around a locus?"],
        ["bacterial genomics"],
        [{"role": "molecule", "type": "string"}, {"role": "gene", "type": "string"}, {"role": "start", "type": "integer"}, {"role": "end", "type": "integer"}, {"role": "strand", "type": "categorical"}],
        level="advanced",
        keywords=["gggenes", "gene neighborhood"],
        sources=[src("gggenes", "https://cran.r-project.org/package=gggenes")],
    ),
    fig(
        "comparative_genomics.plasmid_map",
        "Plasmid / circular molecule map",
        "gene_feature_table",
        ["gggenes", "circlize", "ggplot2"],
        ["What is the annotated layout of a circular plasmid?"],
        ["microbial genomics"],
        [{"role": "start", "type": "integer"}, {"role": "end", "type": "integer"}, {"role": "feature", "type": "string"}],
        level="advanced",
        keywords=["plasmid map"],
    ),
]

# ---- microbiome ----
FIGURES += [
    fig(
        "microbiome.abundance_bar",
        "Taxa abundance stacked bar",
        "taxa_abundance_table",
        ["ggplot2"],
        ["How does taxonomic composition differ across samples?"],
        ["16S", "metagenomics"],
        [{"role": "sample", "type": "string"}, {"role": "taxon", "type": "string"}, {"role": "abundance", "type": "numeric"}],
        keywords=["microbiome bar", "菌群组成"],
    ),
    fig(
        "microbiome.alpha_diversity",
        "Alpha diversity box/violin",
        "alpha_diversity_table",
        ["ggplot2", "ggpubr"],
        ["Do alpha-diversity indices differ by group?"],
        ["16S"],
        [{"role": "sample", "type": "string"}, {"role": "index", "type": "numeric"}, {"role": "group", "type": "categorical"}],
        keywords=["alpha diversity", "Shannon"],
    ),
    fig(
        "microbiome.beta_PCoA",
        "Beta-diversity PCoA",
        "distance_ordination_table",
        ["ggplot2", "vegan"],
        ["Do communities separate in ordination space?"],
        ["16S", "metagenomics"],
        [{"role": "sample", "type": "string"}, {"role": "Axis1", "type": "numeric"}, {"role": "Axis2", "type": "numeric"}, {"role": "group", "type": "categorical"}],
        stats=[{"name": "distance_metric", "default": "bray"}],
        keywords=["PCoA", "beta diversity"],
    ),
    fig(
        "microbiome.taxa_heatmap",
        "Taxa abundance heatmap",
        "taxa_abundance_matrix",
        ["ComplexHeatmap", "ggplot2"],
        ["Which taxa drive sample clustering?"],
        ["16S"],
        [{"role": "taxon", "type": "string"}, {"role": "sample", "type": "string"}, {"role": "abundance", "type": "numeric"}],
        shapes=["matrix"],
        level="advanced",
        keywords=["taxa heatmap"],
    ),
]

# ---- network ----
FIGURES += [
    fig(
        "network.network",
        "Network graph",
        "network_edges",
        ["igraph", "ggraph", "ggplot2"],
        ["How are entities connected in an interaction graph?"],
        ["PPI", "coexpression"],
        [{"role": "source", "type": "string"}, {"role": "target", "type": "string"}],
        optional=[{"role": "weight", "type": "numeric"}],
        level="advanced",
        keywords=["network", "网络图", "ggraph"],
    ),
    fig(
        "network.chord",
        "Chord diagram",
        "network_edges",
        ["circlize"],
        ["How strong are pairwise flows between categories?"],
        ["cell communication", "multiomics"],
        [{"role": "source", "type": "string"}, {"role": "target", "type": "string"}, {"role": "weight", "type": "numeric"}],
        level="advanced",
        keywords=["chord", "弦图"],
    ),
    fig(
        "network.Sankey",
        "Sankey diagram",
        "network_edges",
        ["networkD3", "ggplot2"],
        ["How do quantities flow across sequential categories?"],
        ["clinical pathway", "multiomics"],
        [{"role": "source", "type": "string"}, {"role": "target", "type": "string"}, {"role": "weight", "type": "numeric"}],
        level="advanced",
        keywords=["Sankey", "桑基图"],
    ),
    fig(
        "network.alluvial",
        "Alluvial plot",
        "alluvial_table",
        ["ggalluvial", "ggplot2"],
        ["How do categorical memberships change across stages?"],
        ["single-cell", "clinical"],
        [{"role": "axis1", "type": "categorical"}, {"role": "axis2", "type": "categorical"}, {"role": "freq", "type": "numeric"}],
        level="advanced",
        keywords=["alluvial", "冲积图"],
    ),
    fig(
        "network.arc_diagram",
        "Arc diagram",
        "network_edges",
        ["ggraph", "ggplot2"],
        ["How can one-dimensional node order reveal arcs of interaction?"],
        ["genomics", "PPI"],
        [{"role": "source", "type": "string"}, {"role": "target", "type": "string"}],
        level="experimental",
        keywords=["arc diagram"],
    ),
]

# ---- cell_communication ----
FIGURES += [
    fig(
        "cell_communication.cellchat_circle",
        "Cell–cell communication circle plot",
        "cellchat_network",
        ["CellChat", "circlize"],
        ["Which cell types send/receive inferred signaling?"],
        ["scRNA-seq"],
        [{"role": "source_celltype", "type": "categorical"}, {"role": "target_celltype", "type": "categorical"}, {"role": "weight", "type": "numeric"}],
        level="experimental",
        keywords=["CellChat", "细胞通讯"],
        sources=[src("CellChat", "https://github.com/sqjin/CellChat", "unverified")],
    ),
    fig(
        "cell_communication.ligand_receptor_bubble",
        "Ligand–receptor bubble plot",
        "ligand_receptor_table",
        ["CellChat", "ggplot2"],
        ["Which L–R pairs are enriched between cell types?"],
        ["scRNA-seq"],
        [{"role": "ligand", "type": "string"}, {"role": "receptor", "type": "string"}, {"role": "source", "type": "categorical"}, {"role": "target", "type": "categorical"}, {"role": "score", "type": "numeric"}],
        level="advanced",
        keywords=["ligand receptor", "LR bubble"],
    ),
]

# ---- multiomics ----
FIGURES += [
    fig(
        "multiomics.multiomics_heatmap",
        "Multi-omics linked heatmap",
        "multi_matrix_bundle",
        ["ComplexHeatmap"],
        ["How do aligned multi-omics layers co-vary across samples?"],
        ["TCGA multiomics"],
        [{"role": "sample_id", "type": "string"}, {"role": "layer_matrices", "type": "list_of_matrices"}],
        shapes=["matrix"],
        level="experimental",
        keywords=["multiomics heatmap"],
    ),
    fig(
        "multiomics.correlation_network_multi",
        "Cross-omics correlation network",
        "network_edges",
        ["igraph", "ggraph"],
        ["Which features from different omics layers correlate?"],
        ["multiomics"],
        [{"role": "source", "type": "string"}, {"role": "target", "type": "string"}, {"role": "weight", "type": "numeric"}],
        level="experimental",
        keywords=["multiomics network"],
    ),
]

# ---- time_series ----
FIGURES += [
    fig(
        "time_series.time_course_line",
        "Time-course line plot",
        "time_course_table",
        ["ggplot2"],
        ["How do features change over ordered time points?"],
        ["RNA-seq time series", "longitudinal clinical"],
        [{"role": "feature_id", "type": "string"}, {"role": "time", "type": "numeric"}, {"role": "value", "type": "numeric"}],
        optional=[{"role": "group", "type": "categorical"}],
        keywords=["time course", "时间序列"],
    ),
    fig(
        "time_series.STEM_heatmap",
        "STEM / clustered time-course heatmap",
        "time_course_matrix",
        ["ComplexHeatmap", "ggplot2"],
        ["Which temporal expression modules exist?"],
        ["RNA-seq time series"],
        [{"role": "feature_id", "type": "string"}, {"role": "timepoint_matrix", "type": "numeric_matrix"}],
        shapes=["matrix"],
        level="advanced",
        keywords=["STEM", "temporal heatmap"],
    ),
]


def write_json(path: Path, obj) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    taxonomy = {
        "schema_version": "0.1.0",
        "categories": {
            "basic_statistics": {
                "label": "Basic statistics & distributions",
                "families": [f.split(".", 1)[1] for f in [x["id"] for x in FIGURES if x["category"] == "basic_statistics"]],
            },
            "transcriptomics": {
                "label": "Transcriptomics / differential abundance",
                "families": [f.split(".", 1)[1] for f in [x["id"] for x in FIGURES if x["category"] == "transcriptomics"]],
            },
            "enrichment": {
                "label": "Functional enrichment",
                "families": [x["id"].split(".", 1)[1] for x in FIGURES if x["category"] == "enrichment"],
            },
            "clinical": {
                "label": "Clinical / survival / diagnostic",
                "families": [x["id"].split(".", 1)[1] for x in FIGURES if x["category"] == "clinical"],
            },
            "machine_learning": {
                "label": "Machine learning diagnostics",
                "families": [x["id"].split(".", 1)[1] for x in FIGURES if x["category"] == "machine_learning"],
            },
            "single_cell": {
                "label": "Single-cell transcriptomics",
                "families": [x["id"].split(".", 1)[1] for x in FIGURES if x["category"] == "single_cell"],
            },
            "spatial_omics": {
                "label": "Spatial omics",
                "families": [x["id"].split(".", 1)[1] for x in FIGURES if x["category"] == "spatial_omics"],
            },
            "mutation_genomics": {
                "label": "Mutation & copy-number genomics",
                "families": [x["id"].split(".", 1)[1] for x in FIGURES if x["category"] == "mutation_genomics"],
            },
            "genomics": {
                "label": "Genome tracks & association",
                "families": [x["id"].split(".", 1)[1] for x in FIGURES if x["category"] == "genomics"],
            },
            "comparative_genomics": {
                "label": "Comparative / microbial genomics",
                "families": [x["id"].split(".", 1)[1] for x in FIGURES if x["category"] == "comparative_genomics"],
            },
            "microbiome": {
                "label": "Microbiome ecology",
                "families": [x["id"].split(".", 1)[1] for x in FIGURES if x["category"] == "microbiome"],
            },
            "network": {
                "label": "Networks & flows",
                "families": [x["id"].split(".", 1)[1] for x in FIGURES if x["category"] == "network"],
            },
            "cell_communication": {
                "label": "Cell–cell communication",
                "families": [x["id"].split(".", 1)[1] for x in FIGURES if x["category"] == "cell_communication"],
            },
            "multiomics": {
                "label": "Multi-omics integration views",
                "families": [x["id"].split(".", 1)[1] for x in FIGURES if x["category"] == "multiomics"],
            },
            "time_series": {
                "label": "Time-series / longitudinal",
                "families": [x["id"].split(".", 1)[1] for x in FIGURES if x["category"] == "time_series"],
            },
        },
    }

    data_schemas = {
        "schema_version": "0.1.0",
        "schemas": {
            "differential_expression_table": {
                "required_roles": ["feature_id", "effect_size", "significance"],
                "description": "Tidy DE table (RNA-seq/proteomics/metabolomics)",
            },
            "survival_table": {"required_roles": ["time", "status", "group"]},
            "survival_prediction_table": {"required_roles": ["time", "status", "marker"]},
            "expression_matrix_with_annotation": {
                "required_roles": ["feature_id", "sample_expression"],
                "shape": "matrix",
            },
            "numeric_matrix": {"required_roles": ["feature_or_sample_matrix"], "shape": "matrix"},
            "long_expression_table": {"required_roles": ["feature_id", "group", "expression"]},
            "enrichment_table": {"required_roles": ["term", "significance"]},
            "gsea_result_table": {"required_roles": ["term"]},
            "grouped_numeric_table": {"required_roles": ["group", "value"]},
            "group_numeric_table": {
                "id": "group_numeric_table",
                "description": "Tidy table with categorical group and continuous value",
                "fields": [
                    {"role": "group", "type": "categorical"},
                    {"role": "value", "type": "numeric"},
                    {"role": "sample_id", "type": "string", "optional": True},
                ],
                "required_roles": ["group", "value"],
            },
            "grouped_count_table": {"required_roles": ["category", "value"]},
            "single_numeric_table": {"required_roles": ["value"]},
            "two_numeric_table": {"required_roles": ["x", "y"]},
            "paired_numeric_table": {"required_roles": ["method_a", "method_b"]},
            "binary_prediction_table": {"required_roles": ["score", "label"]},
            "prediction_probability_table": {"required_roles": ["predicted_risk", "observed_outcome"]},
            "cox_result_table": {"required_roles": ["covariate", "HR", "CI_low", "CI_high"]},
            "cox_model_input": {"required_roles": ["covariates", "outcome_model"]},
            "competing_risk_table": {"required_roles": ["time", "event_type", "group"]},
            "patient_timeline_table": {"required_roles": ["patient_id", "start", "end"]},
            "classification_result_table": {"required_roles": ["truth", "prediction"]},
            "feature_importance_table": {"required_roles": ["feature", "importance"]},
            "glmnet_path_table": {"required_roles": ["lambda", "coefficient", "feature"]},
            "model_metric_by_size_table": {"required_roles": ["train_size", "metric", "split"]},
            "single_cell_embedding": {"required_roles": ["cell_id", "dimension_1", "dimension_2"]},
            "single_cell_embedding_with_feature": {
                "required_roles": ["cell_id", "dimension_1", "dimension_2", "feature_value"]
            },
            "single_cell_dot_summary": {"required_roles": ["feature", "identity", "avg_exp", "pct_exp"]},
            "cell_proportion_table": {"required_roles": ["sample", "cell_type"]},
            "trajectory_graph": {"required_roles": ["node", "edge"]},
            "spatial_spot_table": {"required_roles": ["spot_id", "x", "y"]},
            "mutation_table": {"required_roles": ["sample", "gene", "variant_class"]},
            "mutation_summary_table": {"required_roles": ["gene", "frequency"]},
            "mutation_protein_table": {"required_roles": ["gene", "aa_position", "variant_class"]},
            "cnv_segment_table": {"required_roles": ["sample", "chrom", "start", "end", "segment_mean"]},
            "tmb_table": {"required_roles": ["sample", "TMB"]},
            "genomic_interval_table": {"required_roles": ["chrom", "start", "end", "score"]},
            "gwas_association_table": {"required_roles": ["chrom", "position", "pvalue"]},
            "multi_track_genomic_table": {"required_roles": ["chrom", "start", "end"]},
            "tree_newick": {"required_roles": ["tree"]},
            "tree_with_metadata": {"required_roles": ["tree", "tip_metadata"]},
            "tree_with_matrix": {"required_roles": ["tree", "feature_matrix"]},
            "gene_pa_matrix": {"required_roles": ["genome", "gene", "presence"], "shape": "matrix"},
            "synteny_link_table": {"required_roles": ["genome_a", "genome_b", "start_a", "start_b"]},
            "gene_feature_table": {"required_roles": ["start", "end", "feature"]},
            "taxa_abundance_table": {"required_roles": ["sample", "taxon", "abundance"]},
            "taxa_abundance_matrix": {"required_roles": ["taxon", "sample", "abundance"], "shape": "matrix"},
            "alpha_diversity_table": {"required_roles": ["sample", "index", "group"]},
            "distance_ordination_table": {"required_roles": ["sample", "Axis1", "Axis2", "group"]},
            "network_edges": {"required_roles": ["source", "target"]},
            "alluvial_table": {"required_roles": ["axis1", "axis2", "freq"]},
            "cellchat_network": {"required_roles": ["source_celltype", "target_celltype", "weight"]},
            "ligand_receptor_table": {"required_roles": ["ligand", "receptor", "source", "target", "score"]},
            "multi_matrix_bundle": {"required_roles": ["sample_id", "layer_matrices"]},
            "time_course_table": {"required_roles": ["feature_id", "time", "value"]},
            "time_course_matrix": {"required_roles": ["feature_id", "timepoint_matrix"], "shape": "matrix"},
        },
    }

    packages = {
        "schema_version": "0.1.0",
        "packages": [],
    }
    package_specs = [
        ("ggplot2", ["visualization"], "CRAN", True, "https://ggplot2.tidyverse.org/"),
        ("ggrepel", ["visualization", "transcriptomics"], "CRAN", True, "https://cran.r-project.org/package=ggrepel"),
        ("ggpubr", ["visualization", "statistics"], "CRAN", False, "https://cran.r-project.org/package=ggpubr"),
        ("ggdist", ["visualization", "uncertainty"], "CRAN", False, "https://cran.r-project.org/package=ggdist"),
        ("ggridges", ["visualization"], "CRAN", False, "https://cran.r-project.org/package=ggridges"),
        ("ggbeeswarm", ["visualization"], "CRAN", False, "https://cran.r-project.org/package=ggbeeswarm"),
        ("ComplexHeatmap", ["heatmap", "mutation_genomics"], "Bioconductor", False, "https://bioconductor.org/packages/ComplexHeatmap/"),
        ("circlize", ["circos", "network"], "CRAN", False, "https://cran.r-project.org/package=circlize"),
        ("clusterProfiler", ["enrichment"], "Bioconductor", False, "https://bioconductor.org/packages/clusterProfiler/"),
        ("enrichplot", ["enrichment"], "Bioconductor", False, "https://bioconductor.org/packages/enrichplot/"),
        ("survival", ["clinical"], "CRAN", False, "https://cran.r-project.org/package=survival"),
        ("survminer", ["clinical"], "CRAN", False, "https://cran.r-project.org/package=survminer"),
        ("timeROC", ["clinical"], "CRAN", False, "https://cran.r-project.org/package=timeROC"),
        ("pROC", ["clinical", "machine_learning"], "CRAN", False, "https://cran.r-project.org/package=pROC"),
        ("rmda", ["clinical"], "CRAN", False, "https://cran.r-project.org/package=rmda"),
        ("rms", ["clinical"], "CRAN", False, "https://cran.r-project.org/package=rms"),
        ("Seurat", ["single_cell", "spatial_omics"], "CRAN", False, "https://satijalab.org/seurat/"),
        ("patchwork", ["composition"], "CRAN", True, "https://cran.r-project.org/package=patchwork"),
        ("maftools", ["mutation_genomics"], "Bioconductor", False, "https://bioconductor.org/packages/maftools/"),
        ("ggtree", ["comparative_genomics"], "Bioconductor", False, "https://bioconductor.org/packages/ggtree/"),
        ("ggtreeExtra", ["comparative_genomics"], "Bioconductor", False, "https://bioconductor.org/packages/ggtreeExtra/"),
        ("gggenes", ["comparative_genomics"], "CRAN", False, "https://cran.r-project.org/package=gggenes"),
        ("gggenomes", ["comparative_genomics"], "GitHub", False, "https://github.com/thackl/gggenomes"),
        ("igraph", ["network"], "CRAN", False, "https://cran.r-project.org/package=igraph"),
        ("ggraph", ["network"], "CRAN", False, "https://cran.r-project.org/package=ggraph"),
        ("CellChat", ["cell_communication"], "GitHub", False, "https://github.com/sqjin/CellChat"),
        ("glmnet", ["machine_learning"], "CRAN", False, "https://cran.r-project.org/package=glmnet"),
        ("vegan", ["microbiome"], "CRAN", False, "https://cran.r-project.org/package=vegan"),
        ("networkD3", ["network"], "CRAN", False, "https://cran.r-project.org/package=networkD3"),
        ("ggalluvial", ["network"], "CRAN", False, "https://cran.r-project.org/package=ggalluvial"),
        ("qqman", ["genomics"], "CRAN", False, "https://cran.r-project.org/package=qqman"),
        ("cmprsk", ["clinical"], "CRAN", False, "https://cran.r-project.org/package=cmprsk"),
        ("GOSemSim", ["enrichment"], "Bioconductor", False, "https://bioconductor.org/packages/GOSemSim/"),
        ("slingshot", ["single_cell"], "Bioconductor", False, "https://bioconductor.org/packages/slingshot/"),
        ("ggbio", ["genomics"], "Bioconductor", False, "https://bioconductor.org/packages/ggbio/"),
        ("forestplot", ["clinical"], "CRAN", False, "https://cran.r-project.org/package=forestplot"),
    ]
    fig_by_pkg: dict[str, list[str]] = {}
    for figure in FIGURES:
        for pkg in figure["recommended_r_packages"]:
            fig_by_pkg.setdefault(pkg, []).append(figure["id"])
    for name, domain, install, required, url in package_specs:
        packages["packages"].append(
            {
                "package": name,
                "domain": domain,
                "figure_types": fig_by_pkg.get(name, []),
                "install_source": install,
                "required_for_core": required,
                "source": url,
            }
        )

    compositions = {
        "schema_version": "0.1.0",
        "compositions": [
            {
                "composition_id": "rna_seq_differential_standard",
                "scientific_goal": "Present differential transcriptomic changes",
                "recommended_panels": [
                    "transcriptomics.volcano",
                    "transcriptomics.DEG_heatmap",
                    "enrichment.GSEA_running_score",
                ],
            },
            {
                "composition_id": "prognostic_model_standard",
                "scientific_goal": "Present prognostic model performance",
                "recommended_panels": [
                    "clinical.Kaplan_Meier",
                    "clinical.time_dependent_ROC",
                    "clinical.Cox_forest",
                    "clinical.nomogram",
                ],
            },
            {
                "composition_id": "single_cell_annotation_standard",
                "scientific_goal": "Present cell identity annotation evidence",
                "recommended_panels": [
                    "single_cell.UMAP",
                    "single_cell.DotPlot",
                    "single_cell.Violin_sc",
                ],
            },
            {
                "composition_id": "mutation_landscape_standard",
                "scientific_goal": "Present somatic alteration landscape",
                "recommended_panels": [
                    "mutation_genomics.oncoplot",
                    "mutation_genomics.TMB",
                    "mutation_genomics.mutation_frequency",
                ],
            },
            {
                "composition_id": "microbiome_ecology_standard",
                "scientific_goal": "Present community composition and diversity",
                "recommended_panels": [
                    "microbiome.abundance_bar",
                    "microbiome.alpha_diversity",
                    "microbiome.beta_PCoA",
                ],
            },
            {
                "composition_id": "enrichment_suite",
                "scientific_goal": "Present ORA/GSEA functional interpretation",
                "recommended_panels": [
                    "enrichment.ORA_dotplot",
                    "enrichment.GSEA_running_score",
                    "enrichment.enrichment_emap",
                ],
            },
            {
                "composition_id": "diagnostic_biomarker",
                "scientific_goal": "Present diagnostic marker performance",
                "recommended_panels": ["clinical.ROC", "clinical.calibration", "clinical.decision_curve"],
            },
            {
                "composition_id": "comparative_genome_suite",
                "scientific_goal": "Present phylogeny with gene content",
                "recommended_panels": [
                    "comparative_genomics.phylogenetic_tree",
                    "comparative_genomics.tree_heatmap",
                    "comparative_genomics.gene_presence_absence",
                ],
            },
        ],
    }

    # FigureYa public module list → family mapping (metadata only; no Rmd copy)
    figureya_modules = [
        ("FigureYa59volcanoV2", "transcriptomics.volcano", "RNA-seq DE", "volcano"),
        ("FigureYa321volcanoSE", "transcriptomics.volcano", "RNA-seq DE", "volcano SE"),
        ("FigureYa135multiVolcano", "transcriptomics.multi_volcano", "multi-contrast DE", "multi volcano"),
        ("FigureYa9heatmap", "transcriptomics.DEG_heatmap", "expression matrix", "heatmap"),
        ("FigureYa91cluster_heatmap", "transcriptomics.DEG_heatmap", "clustered heatmap", "heatmap"),
        ("FigureYa101PCA", "transcriptomics.PCA", "sample ordination", "PCA"),
        ("FigureYa244PCAPlot", "transcriptomics.PCA", "PCA", "PCA"),
        ("FigureYa12box", "basic_statistics.boxplot", "group comparison", "boxplot"),
        ("FigureYa162boxViolin", "basic_statistics.violin", "box+violin", "violin"),
        ("FigureYa1survivalCurve_update", "clinical.Kaplan_Meier", "survival", "KM"),
        ("FigureYa36nSurvV3", "clinical.Kaplan_Meier", "survival", "KM"),
        ("FigureYa24ROC", "clinical.ROC", "diagnostic", "ROC"),
        ("FigureYa85timeROC", "clinical.time_dependent_ROC", "prognostic", "timeROC"),
        ("FigureYa33DCA_update", "clinical.decision_curve", "clinical benefit", "DCA"),
        ("FigureYa30nomogram_update", "clinical.nomogram", "prognostic model", "nomogram"),
        ("FigureYa138NiceCalibration", "clinical.calibration", "calibration", "calibration"),
        ("FigureYa6rHRsV2", "clinical.Cox_forest", "hazard ratios", "forest"),
        ("FigureYa186swimmerplot", "clinical.swimmer", "patient timeline", "swimmer"),
        ("FigureYa18oncoplot_update", "mutation_genomics.oncoplot", "mutation landscape", "oncoplot"),
        ("FigureYa42oncoprintV2_update", "mutation_genomics.oncoplot", "oncoPrint", "oncoplot"),
        ("FigureYa19Lollipop", "mutation_genomics.lollipop", "protein mutations", "lollipop"),
        ("FigureYa51TMB_update", "mutation_genomics.TMB", "TMB", "TMB"),
        ("FigureYa139TMB_titv", "mutation_genomics.TiTv", "Ti/Tv", "titv"),
        ("FigureYa288MutualExclusivity", "mutation_genomics.mutual_exclusivity", "exclusivity", "mutex"),
        ("FigureYa60GSEA_clusterProfilerV2", "enrichment.GSEA_running_score", "GSEA", "GSEA"),
        ("FigureYa13GSEA_Java_update", "enrichment.GSEA_running_score", "GSEA", "GSEA"),
        ("FigureYa83enrichment", "enrichment.ORA_dotplot", "ORA", "enrichment"),
        ("FigureYa52GOplot", "enrichment.GO_hierarchy", "GO", "GO"),
        ("FigureYa25Sankey_update", "network.Sankey", "flow", "Sankey"),
        ("FigureYa26circos_R", "genomics.circos_genome", "circos", "circos"),
        ("FigureYa43ManhattanV2", "genomics.manhattan", "GWAS", "manhattan"),
        ("FigureYa229PCOA", "microbiome.beta_PCoA", "ordination", "PCoA"),
        ("FigureYa31lasso_update", "machine_learning.lasso_path", "regularization", "lasso"),
        ("FigureYa306slingshot", "single_cell.trajectory", "trajectory", "slingshot"),
        ("FigureYa235scDEG", "single_cell.UMAP", "sc DEG context", "scDEG"),
        ("FigureYa178receptorLigand", "cell_communication.ligand_receptor_bubble", "LR", "LR"),
        ("FigureYa81immune_network", "network.network", "immune network", "network"),
        ("FigureYa112venn", "basic_statistics.barplot", "set overlap (mapped loosely)", "venn"),
        ("FigureYa37correlationV2_update", "basic_statistics.scatter", "correlation", "scatter"),
        ("FigureYa126CorrelationHeatmap", "basic_statistics.correlation_heatmap", "correlation heatmap", "heatmap"),
        ("FigureYa260CNV", "mutation_genomics.CNV_plot", "CNV", "CNV"),
        ("FigureYa307CNVHeatmap", "mutation_genomics.CNV_plot", "CNV heatmap", "CNV"),
        ("FigureYa98STEMheatmapV2", "time_series.STEM_heatmap", "temporal modules", "STEM"),
    ]
    source_registry = {
        "schema_version": "0.1.0",
        "notes": [
            "FigureYa mappings are scientific abstractions only.",
            "Do not copy FigureYa Rmd/source into SCIPlot.",
            "Module inventory from https://github.com/ying-ge/FigureYa/.github/docs/all_included.txt",
        ],
        "figureya": {
            "source_url": "https://github.com/ying-ge/FigureYa",
            "paper_doi": "10.1002/imm3.70005",
            "modules_listed_in_all_included": 199,
            "modules_mapped_here": len(figureya_modules),
            "mapped_figure_families": sorted({m[1] for m in figureya_modules}),
            "mappings": [
                {
                    "external_source": "FigureYa",
                    "external_module": mod,
                    "mapped_figure_family": fam,
                    "data_context": ctx,
                    "scientific_purpose": purpose,
                    "r_packages_if_publicly_documented": [],
                    "source_url": f"https://github.com/ying-ge/FigureYa/tree/main/{mod}",
                    "verification_status": "verified",
                }
                for mod, fam, ctx, purpose in figureya_modules
            ],
        },
    }

    catalog = {
        "schema_version": "0.1.0",
        "description": "SCIPlot Scientific Figure Catalog — ontology only, not implementations",
        "figure_count": len(FIGURES),
        "figures": FIGURES,
    }

    write_json(ROOT / "taxonomy.json", taxonomy)
    write_json(ROOT / "data_schemas.json", data_schemas)
    write_json(ROOT / "package_registry.json", packages)
    write_json(ROOT / "composition_rules.json", compositions)
    write_json(ROOT / "source_registry.json", source_registry)
    write_json(ROOT / "catalog.json", catalog)

    # Per-figure files in category folders
    for figure in FIGURES:
        category = figure["category"]
        family = figure["id"].split(".", 1)[1]
        write_json(ROOT / category / f"{family}.json", figure)
        readme = ROOT / category / "README.md"
        if not readme.exists():
            readme.write_text(
                f"# {category}\n\nFigure families in this category are listed in `../catalog.json` and as individual JSON files here.\n",
                encoding="utf-8",
            )

    print(f"Wrote {len(FIGURES)} figure families")


if __name__ == "__main__":
    main()
