"""Scatter code-generation strategy — GenericFigureSpecification → ggplot2 R."""

from __future__ import annotations

from pathlib import Path

from core.strategies.base import CodeGenerationStrategy
from schemas.generic_figure_spec import GenericFigureSpecification

FIGURE_ID = "basic_statistics.scatter"


def _r_str(value: object) -> str:
    text = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{text}"'


class ScatterStrategy(CodeGenerationStrategy):
    figure_definition_id = FIGURE_ID

    def generate(
        self,
        spec: GenericFigureSpecification,
        output_path: str | Path | None = None,
    ) -> str:
        if spec.figure_definition_id != self.figure_definition_id:
            raise ValueError(
                f"ScatterStrategy only supports {self.figure_definition_id}, "
                f"got {spec.figure_definition_id}"
            )
        code = self._render(spec)
        if output_path is not None:
            path = Path(output_path)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(code, encoding="utf-8")
        return code

    def _render(self, spec: GenericFigureSpecification) -> str:
        mapping = spec.data_mapping
        x_col = mapping.get("x")
        y_col = mapping.get("y")
        if not x_col or not y_col:
            raise ValueError("ScatterStrategy requires data_mapping roles: x, y")
        size_col = mapping.get("size") or ""
        group_col = mapping.get("group") or ""

        visual = spec.visual_parameters
        output = spec.output or {"pdf": True, "svg": True, "png": True}
        source = spec.data_source or "input.csv"
        alpha = float(visual.get("alpha", 0.7))
        point_size = float(visual.get("point_size", 1.6))
        size_max = float(visual.get("size_max", 6.0))
        line_width = float(visual.get("line_width", 0.5))
        width_mm = float(visual.get("width_mm", 89))
        height_mm = float(visual.get("height_mm", 70))
        font_size = float(visual.get("font_size", 7))
        legend_position = str(visual.get("legend_position", "right"))
        border = str(visual.get("border", "none")).lower()
        dpi = int(visual.get("dpi", 600))
        point_color = str(visual.get("point_color", "#3C5488"))

        aes_parts = ["x = .data[[x_col]]", "y = .data[[y_col]]"]
        if size_col:
            aes_parts.append("size = .data[[size_col]]")
        if group_col:
            aes_parts.append("color = .data[[group_col]]")
        aes_block = ", ".join(aes_parts)

        if group_col:
            # Group drives color scale; fixed point_color is not used.
            geom = "geom_point(alpha = point_alpha)"
        elif size_col:
            geom = "geom_point(alpha = point_alpha, color = point_color)"
        else:
            geom = "geom_point(alpha = point_alpha, size = point_size, color = point_color)"
        # Bubble plots: point_size refine maps to size_max (scale_size_area).
        size_scale = (
            " +\n  scale_size_area(max_size = size_max)"
            if size_col
            else ""
        )

        if border == "full":
            border_theme = (
                "    panel.border = element_rect(colour = \"black\", fill = NA, "
                "linewidth = line_width),\n"
                "    axis.line = element_blank()"
            )
        else:
            border_theme = (
                "    panel.border = element_blank(),\n"
                "    axis.line = element_line(linewidth = line_width, colour = \"black\")"
            )

        save_parts: list[str] = []
        if output.get("pdf", True):
            save_parts.append(
                """
ggsave("scatter.pdf", plot = p, width = width_mm, height = height_mm, units = "mm", device = cairo_pdf)"""
            )
        if output.get("svg", True):
            save_parts.append(
                """
ggsave("scatter.svg", plot = p, width = width_mm, height = height_mm, units = "mm", device = svglite)"""
            )
        if output.get("png", True):
            save_parts.append(
                """
ggsave("scatter.png", plot = p, width = width_mm, height = height_mm, units = "mm", dpi = dpi)"""
            )
        save_block = "\n".join(save_parts)

        size_check = ""
        if size_col:
            size_check = """
df[[size_col]] <- as.numeric(df[[size_col]])
"""
        group_check = ""
        if group_col:
            group_check = """
df[[group_col]] <- as.factor(as.character(df[[group_col]]))
"""

        return f"""# scatter.R
# Generated by SCIPlot Generic Figure Engine — ScatterStrategy
# Source: GenericFigureSpecification (no free-text NL, no LLM R)

suppressPackageStartupMessages({{
  library(ggplot2)
  library(svglite)
}})

input_file <- {_r_str(source)}
x_col <- {_r_str(x_col)}
y_col <- {_r_str(y_col)}
size_col <- {_r_str(size_col)}
group_col <- {_r_str(group_col)}
point_size <- {point_size}
size_max <- {size_max}
point_alpha <- {alpha}
line_width <- {line_width}
width_mm <- {width_mm}
height_mm <- {height_mm}
dpi <- {dpi}
font_size <- {font_size}
legend_position <- {_r_str(legend_position)}
point_color <- {_r_str(point_color)}

if (!file.exists(input_file)) {{
  stop("Input table not found: ", input_file)
}}
df <- read.csv(input_file, stringsAsFactors = FALSE, check.names = FALSE, na.strings = c("NA", "", "NaN"))

required_cols <- c(x_col, y_col)
if (nzchar(size_col)) required_cols <- c(required_cols, size_col)
if (nzchar(group_col)) required_cols <- c(required_cols, group_col)
missing_cols <- setdiff(required_cols, names(df))
if (length(missing_cols) > 0) {{
  stop("Missing columns in input table: ", paste(missing_cols, collapse = ", "))
}}

df[[x_col]] <- as.numeric(df[[x_col]])
df[[y_col]] <- as.numeric(df[[y_col]])
{size_check}{group_check}df <- df[is.finite(df[[x_col]]) & is.finite(df[[y_col]]), , drop = FALSE]

p <- ggplot(df, aes({aes_block})) +
  {geom}{size_scale} +
  theme_classic(base_size = font_size) +
  theme(
    legend.position = legend_position,
{border_theme}
  ) +
  labs(x = x_col, y = y_col)

{save_block}
"""
