# volcano.R
# Generated by SCIPlot AI Volcano R Code Agent from FigureSpecification.
# Packages: ggplot2, ggrepel, svglite

suppressPackageStartupMessages({
  library(ggplot2)
  library(ggrepel)
  library(svglite)
})

# ---- Data interface (column names from FigureSpecification) ----
input_file <- "input.csv"
gene_col <- "gene"
log2fc_col <- "log2FoldChange"
fdr_col <- "padj"

log2fc_threshold <- 1.0
fdr_threshold <- 0.05

point_size <- 1.5
point_alpha <- 0.7
line_width <- 0.5
threshold_line_width <- 0.35

width_mm <- 89.0
height_mm <- 70.0
dpi <- 600

font_family <- "Arial"
axis_text_size <- 7.0
axis_title_size <- 7.0
legend_size <- 7.0

# Windows pdf() cannot load Arial as a CID font. cairo_pdf/svglite can.

col_up <- "#E64B35"
col_down <- "#4DBBD5"
col_ns <- "#B0B0B0"

label_enabled <- TRUE
label_mode <- "top_n"
label_top_n <- 10
label_genes <- character(0)

# ---- Read and check ----
if (!file.exists(input_file)) {
  stop("Input table not found: ", input_file)
}
df <- read.csv(input_file, stringsAsFactors = FALSE, check.names = FALSE, na.strings = c("NA", "", "NaN"))

required_cols <- c(gene_col, log2fc_col, fdr_col)
missing_cols <- setdiff(required_cols, names(df))
if (length(missing_cols) > 0) {
  stop("Missing columns in input table: ", paste(missing_cols, collapse = ", "))
}

# Map specification columns onto canonical volcano fields: gene / log2FC / FDR
df$gene <- as.character(df[[gene_col]])
df$log2FC <- as.numeric(df[[log2fc_col]])
df$FDR <- as.numeric(df[[fdr_col]])
df <- df[is.finite(df$log2FC) & is.finite(df$FDR) & df$FDR >= 0, , drop = FALSE]
df$FDR[df$FDR == 0] <- min(df$FDR[df$FDR > 0], na.rm = TRUE) / 10
df$negLog10 <- -log10(df$FDR)

# ---- Classify Up / Down / NS ----
df$group <- "NS"
df$group[df$log2FC >= log2fc_threshold & df$FDR <= fdr_threshold] <- "Up"
df$group[df$log2FC <= -log2fc_threshold & df$FDR <= fdr_threshold] <- "Down"
df$group <- factor(df$group, levels = c("Up", "Down", "NS"))

# ---- Gene labels ----
df$label <- NA_character_
if (isTRUE(label_enabled)) {
  if (identical(label_mode, "gene_list")) {
    df$label[df$gene %in% label_genes] <- df$gene[df$gene %in% label_genes]
  } else {
    ranked <- df[df$group %in% c("Up", "Down"), , drop = FALSE]
    ranked <- ranked[order(ranked$FDR, -abs(ranked$log2FC)), , drop = FALSE]
    top_genes <- unique(head(ranked$gene, label_top_n))
    df$label[df$gene %in% top_genes] <- df$gene[df$gene %in% top_genes]
  }
}

# ---- ggplot: points, threshold lines, gene labels, publication theme ----
p <- ggplot(df, aes(x = log2FC, y = negLog10, colour = group)) +
  geom_point(size = point_size, alpha = point_alpha, stroke = 0, na.rm = TRUE) +
  geom_vline(
    xintercept = c(-log2fc_threshold, log2fc_threshold),
    linetype = "dashed",
    linewidth = threshold_line_width,
    colour = "#555555"
  ) +
  geom_hline(
    yintercept = -log10(fdr_threshold),
    linetype = "dashed",
    linewidth = threshold_line_width,
    colour = "#555555"
  ) +
  geom_text_repel(
    aes(label = label),
    size = axis_text_size / 2.845,
    family = font_family,
    colour = "black",
    max.overlaps = 20,
    min.segment.length = 0,
    segment.size = 0.3,
    seed = 42,
    na.rm = TRUE
  ) +
  scale_colour_manual(
    values = c(Up = col_up, Down = col_down, NS = col_ns),
    breaks = c("Up", "Down", "NS"),
    name = NULL
  ) +
  labs(x = "log2 fold change", y = expression(-log[10]("FDR"))) +
  coord_cartesian(clip = "off") +
  theme_classic(base_family = font_family) +
  theme(
    axis.text = element_text(size = axis_text_size, colour = "black"),
    axis.title = element_text(size = axis_title_size, colour = "black"),
    legend.text = element_text(size = legend_size, colour = "black"),
    legend.title = element_blank(),
    legend.position = "right",
    axis.line = element_line(linewidth = line_width, colour = "black"),
    axis.ticks = element_line(linewidth = line_width, colour = "black"),
    plot.background = element_rect(fill = "white", colour = NA),
    panel.background = element_rect(fill = "white", colour = NA),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()
  )

# ---- Export pdf / svg / png ----
pdf_device <- if (isTRUE(capabilities("cairo"))) cairo_pdf else pdf
export_errors <- character(0)
safe_ggsave <- function(...) {
  tryCatch(
    ggsave(...),
    error = function(e) {
      export_errors <<- c(export_errors, conditionMessage(e))
      message("ggsave failed: ", conditionMessage(e))
    }
  )
}
safe_ggsave("volcano.pdf", plot = p, width = width_mm, height = height_mm, units = "mm", device = pdf_device, bg = "white")
safe_ggsave("volcano.svg", plot = p, width = width_mm, height = height_mm, units = "mm", device = svglite::svglite, bg = "white")
safe_ggsave("volcano.png", plot = p, width = width_mm, height = height_mm, units = "mm", dpi = dpi, bg = "white")
if (length(export_errors) > 0) {
  stop(paste(export_errors, collapse = "; "), call. = FALSE)
}
