# boxplot.R
# Generated by SCIPlot Generic Figure Engine — BoxplotStrategy
# Source: GenericFigureSpecification (no free-text NL)

suppressPackageStartupMessages({
  library(ggplot2)
  library(svglite)
})

input_file <- "input.csv"
group_col <- "group"
value_col <- "value"

point_size <- 1.5
point_alpha <- 0.75
line_width <- 0.5
width_mm <- 89.0
height_mm <- 70.0
dpi <- 600
font_size <- 7.0
legend_position <- "right"
variant <- "boxplot"

if (!file.exists(input_file)) {
  stop("Input table not found: ", input_file)
}
df <- read.csv(input_file, stringsAsFactors = FALSE, check.names = FALSE, na.strings = c("NA", "", "NaN"))

required_cols <- c(group_col, value_col)
missing_cols <- setdiff(required_cols, names(df))
if (length(missing_cols) > 0) {
  stop("Missing columns in input table: ", paste(missing_cols, collapse = ", "))
}

df[[group_col]] <- as.factor(as.character(df[[group_col]]))
df[[value_col]] <- as.numeric(df[[value_col]])
df <- df[is.finite(df[[value_col]]), , drop = FALSE]

p <- ggplot(df, aes(x = `group`, y = `value`, fill = `group`)) +
  geom_boxplot(linewidth = line_width, alpha = point_alpha, outlier.size = point_size) +
  geom_jitter(width = 0.15, height = 0, size = point_size, alpha = min(1, point_alpha + 0.15), color = "#333333") +
  theme_classic(base_size = font_size) +
  theme(
    legend.position = legend_position,
    panel.border = element_blank(),
    axis.line = element_line(linewidth = line_width, colour = "black")
  ) +
  labs(x = group_col, y = value_col)


ggsave(
  "boxplot.pdf",
  plot = p,
  width = width_mm,
  height = height_mm,
  units = "mm",
  device = cairo_pdf
)

ggsave(
  "boxplot.svg",
  plot = p,
  width = width_mm,
  height = height_mm,
  units = "mm",
  device = svglite
)

ggsave(
  "boxplot.png",
  plot = p,
  width = width_mm,
  height = height_mm,
  units = "mm",
  dpi = dpi
)
