"""Volcano R Code Generation Agent (V0.1).

Turns a FigureSpecification into a runnable ggplot2/ggrepel/svglite script.
Does not read natural language, execute R, or infer figure type from text.
Every visual and statistical constant is copied from the specification.
"""

from __future__ import annotations

from pathlib import Path
from typing import Union

from schemas.figure_spec import FigureSpecification, FigureType, GridStyle, BorderStyle

SpecLike = Union[FigureSpecification, dict]


def _r_str(value: str) -> str:
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _r_bool(value: bool) -> str:
    return "TRUE" if value else "FALSE"


def _r_chr_vec(items: list[str]) -> str:
    if not items:
        return "character(0)"
    return "c(" + ", ".join(_r_str(item) for item in items) + ")"


class VolcanoRCodeAgent:
    """Compile FigureSpecification → volcano.R source text."""

    def generate(
        self,
        spec: SpecLike,
        output_path: str | Path | None = None,
    ) -> str:
        if not isinstance(spec, FigureSpecification):
            spec = FigureSpecification.model_validate(spec)
        if spec.figure_type is not FigureType.VOLCANO:
            raise ValueError(
                "VolcanoRCodeAgent requires spec.figure_type='volcano'; "
                f"got '{spec.figure_type.value}'."
            )
        missing = spec.plot.blocking_missing()
        if missing:
            raise ValueError(
                "FigureSpecification is incomplete for R generation: " + ", ".join(missing)
            )

        code = self._render(spec)
        if output_path is not None:
            path = Path(output_path)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(code, encoding="utf-8")
        return code

    def _render(self, spec: FigureSpecification) -> str:
        plot = spec.plot
        source = plot.data.source or "input.csv"
        gene_col = plot.data.gene_column
        log2fc_col = plot.data.log2fc_column
        sig_col = plot.data.significance_column
        metric = plot.statistics.significance_metric.value
        y_axis = "-log10(FDR)" if metric == "fdr" else "-log10(P)"

        grid_theme = self._grid_theme(spec.theme.grid)
        border_theme = self._border_theme(spec.theme.border, spec.geometry.line_width)
        fill = "NA" if spec.theme.background == "transparent" else _r_str(spec.theme.background)
        save_blocks = self._save_blocks(spec)

        return f"""# volcano.R
# Generated by SCIPlot AI Volcano R Code Agent from FigureSpecification.
# Packages: ggplot2, ggrepel, svglite

suppressPackageStartupMessages({{
  library(ggplot2)
  library(ggrepel)
  library(svglite)
}})

# ---- Data interface (column names from FigureSpecification) ----
input_file <- {_r_str(source)}
gene_col <- {_r_str(gene_col)}
log2fc_col <- {_r_str(log2fc_col)}
fdr_col <- {_r_str(sig_col)}

log2fc_threshold <- {plot.statistics.log2fc_threshold}
fdr_threshold <- {plot.statistics.fdr_threshold}

point_size <- {spec.geometry.point_size}
point_alpha <- {spec.geometry.alpha}
line_width <- {spec.geometry.line_width}
threshold_line_width <- {spec.geometry.threshold_line_width}

width_mm <- {spec.size.width_mm}
height_mm <- {spec.size.height_mm}
dpi <- {spec.size.dpi}

font_family <- {_r_str(spec.font.font_family)}
axis_text_size <- {spec.font.axis_text_size}
axis_title_size <- {spec.font.axis_title_size}
legend_size <- {spec.font.legend_size}

# Windows pdf() cannot load Arial as a CID font. cairo_pdf/svglite can.

col_up <- {_r_str(plot.colors.up)}
col_down <- {_r_str(plot.colors.down)}
col_ns <- {_r_str(plot.colors.ns)}

label_enabled <- {_r_bool(plot.labels.enabled)}
label_mode <- {_r_str(plot.labels.mode)}
label_top_n <- {plot.labels.top_n}
label_genes <- {_r_chr_vec(plot.labels.genes)}

# ---- Read and check ----
if (!file.exists(input_file)) {{
  stop("Input table not found: ", input_file)
}}
df <- read.csv(input_file, stringsAsFactors = FALSE, check.names = FALSE, na.strings = c("NA", "", "NaN"))

required_cols <- c(gene_col, log2fc_col, fdr_col)
missing_cols <- setdiff(required_cols, names(df))
if (length(missing_cols) > 0) {{
  stop("Missing columns in input table: ", paste(missing_cols, collapse = ", "))
}}

# Map specification columns onto canonical volcano fields: gene / log2FC / FDR
df$gene <- as.character(df[[gene_col]])
df$log2FC <- as.numeric(df[[log2fc_col]])
df$FDR <- as.numeric(df[[fdr_col]])
df <- df[is.finite(df$log2FC) & is.finite(df$FDR) & df$FDR >= 0, , drop = FALSE]
df$FDR[df$FDR == 0] <- min(df$FDR[df$FDR > 0], na.rm = TRUE) / 10
df$negLog10 <- -log10(df$FDR)

# ---- Classify Up / Down / NS ----
df$group <- "NS"
df$group[df$log2FC >= log2fc_threshold & df$FDR <= fdr_threshold] <- "Up"
df$group[df$log2FC <= -log2fc_threshold & df$FDR <= fdr_threshold] <- "Down"
df$group <- factor(df$group, levels = c("Up", "Down", "NS"))

# ---- Gene labels ----
df$label <- NA_character_
if (isTRUE(label_enabled)) {{
  if (identical(label_mode, "gene_list")) {{
    df$label[df$gene %in% label_genes] <- df$gene[df$gene %in% label_genes]
  }} else {{
    ranked <- df[df$group %in% c("Up", "Down"), , drop = FALSE]
    ranked <- ranked[order(ranked$FDR, -abs(ranked$log2FC)), , drop = FALSE]
    top_genes <- unique(head(ranked$gene, label_top_n))
    df$label[df$gene %in% top_genes] <- df$gene[df$gene %in% top_genes]
  }}
}}

# ---- ggplot: points, threshold lines, gene labels, publication theme ----
p <- ggplot(df, aes(x = log2FC, y = negLog10, colour = group)) +
  geom_point(size = point_size, alpha = point_alpha, stroke = 0, na.rm = TRUE) +
  geom_vline(
    xintercept = c(-log2fc_threshold, log2fc_threshold),
    linetype = "dashed",
    linewidth = threshold_line_width,
    colour = "#555555"
  ) +
  geom_hline(
    yintercept = -log10(fdr_threshold),
    linetype = "dashed",
    linewidth = threshold_line_width,
    colour = "#555555"
  ) +
  geom_text_repel(
    aes(label = label),
    size = axis_text_size / 2.845,
    family = font_family,
    colour = "black",
    max.overlaps = 20,
    min.segment.length = 0,
    segment.size = 0.3,
    seed = 42,
    na.rm = TRUE
  ) +
  scale_colour_manual(
    values = c(Up = col_up, Down = col_down, NS = col_ns),
    breaks = c("Up", "Down", "NS"),
    name = NULL
  ) +
  labs(x = "log2 fold change", y = {y_lab_expr(y_axis)}) +
  coord_cartesian(clip = "off") +
  theme_classic(base_family = font_family) +
  theme(
    axis.text = element_text(size = axis_text_size, colour = "black"),
    axis.title = element_text(size = axis_title_size, colour = "black"),
    legend.text = element_text(size = legend_size, colour = "black"),
    legend.title = element_blank(),
    legend.position = {_r_str(spec.theme.legend_position)},
    axis.line = element_line(linewidth = line_width, colour = "black"),
    axis.ticks = element_line(linewidth = line_width, colour = "black"),
    plot.background = element_rect(fill = {fill}, colour = NA),
    panel.background = element_rect(fill = {fill}, colour = NA),
    {grid_theme}
    {border_theme}
  )

# ---- Export pdf / svg / png ----
{save_blocks}
"""


    def _grid_theme(self, grid: GridStyle) -> str:
        if grid is GridStyle.NONE:
            return "panel.grid.major = element_blank(),\n    panel.grid.minor = element_blank(),"
        if grid is GridStyle.MAJOR:
            return (
                "panel.grid.major = element_line(linewidth = 0.2, colour = \"grey90\"),\n"
                "    panel.grid.minor = element_blank(),"
            )
        return (
            "panel.grid.major = element_line(linewidth = 0.2, colour = \"grey90\"),\n"
            "    panel.grid.minor = element_line(linewidth = 0.1, colour = \"grey94\"),"
        )

    def _border_theme(self, border: BorderStyle, line_width: float) -> str:
        if border in {BorderStyle.PANEL, BorderStyle.FULL}:
            return (
                f"panel.border = element_rect(colour = \"black\", fill = NA, "
                f"linewidth = {line_width})"
            )
        return "panel.border = element_blank()"

    def _save_blocks(self, spec: FigureSpecification) -> str:
        bg = _r_str(spec.theme.background)
        chunks = [
            "pdf_device <- if (isTRUE(capabilities(\"cairo\"))) cairo_pdf else pdf",
            "export_errors <- character(0)",
            "safe_ggsave <- function(...) {",
            "  tryCatch(",
            "    ggsave(...),",
            "    error = function(e) {",
            "      export_errors <<- c(export_errors, conditionMessage(e))",
            "      message(\"ggsave failed: \", conditionMessage(e))",
            "    }",
            "  )",
            "}",
        ]
        if spec.output.pdf:
            chunks.append(
                "safe_ggsave(\"volcano.pdf\", plot = p, width = width_mm, height = height_mm, "
                f"units = \"mm\", device = pdf_device, bg = {bg})"
            )
        if spec.output.svg:
            chunks.append(
                "safe_ggsave(\"volcano.svg\", plot = p, width = width_mm, height = height_mm, "
                f"units = \"mm\", device = svglite::svglite, bg = {bg})"
            )
        if spec.output.png:
            chunks.append(
                "safe_ggsave(\"volcano.png\", plot = p, width = width_mm, height = height_mm, "
                f"units = \"mm\", dpi = dpi, bg = {bg})"
            )
        chunks.append(
            "if (length(export_errors) > 0) {\n"
            "  stop(paste(export_errors, collapse = \"; \"), call. = FALSE)\n"
            "}"
        )
        return "\n".join(chunks)


def y_lab_expr(plain_fallback: str) -> str:
    if plain_fallback == "-log10(FDR)":
        return 'expression(-log[10]("FDR"))'
    return 'expression(-log[10](italic(P)))'
